apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-compute-quota
  namespace: dev
spec:
  hard:
    pods: "20"
    services: "15"
    configmaps: "30"
    secrets: "30"
    persistentvolumeclaims: "10"
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
