replicaCount: 1

image:
  repository: changeme.azurecr.io/cartservice
  digest: "sha256:replace-me"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  port: 7070
  targetPort: 7070

resources: {}

nodeSelector: {}

tolerations: []
