apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
{{- if .Values.googleDemo.enabled }}
  type: ExternalName
  externalName: {{ .Values.googleDemo.externalName }}
{{- else }}
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
{{- if not .Values.googleDemo.enabled }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
