image:
  repository: acrboutiquedevweu.azurecr.io/currencyservice
  digest: "sha256:0d2ab9517ddcc2100183ff8674802911f93f4f9d8b201e3db8d157c02138f40d"

service:
  port: 7000
  targetPort: 7000

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
