image:
  repository: acrboutiquedevweu.azurecr.io/backend
  digest: "sha256:01042ba10da55fec1c700add1b8fed005234a5c090ff720b09401f5304471b8e"

ingress:
  host: api-dev.boutique.biroltilki.art
  tls:
    secretName: backend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
