image:
  repository: acrboutiquedevweu.azurecr.io/currencyservice
  digest: "sha256:97cb2a5800ebfee5045aabffa389beda9a8ed76a8ba723339ed04a4d22dd5833"

service:
  port: 7000
  targetPort: 7000

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
