image:
  repository: acrboutiquedevweu.azurecr.io/cartservice
  digest: "sha256:a8f8bfc10ed4249452c25afa222f1602a3e7a640a33edc5282bb4228954c2cff"

service:
  port: 7070
  targetPort: 7070

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
