image:
  repository: acrboutiquedevweu.azurecr.io/cartservice
  digest: "sha256:19178ea753747964668a395b189f0840dc3865eb3888dcd9f538b3f43c59fdf0"

service:
  port: 7070
  targetPort: 7070

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
