image:
  repository: acrboutiquedevweu.azurecr.io/frontend
  digest: "sha256:a7ea6e5a8b398ef9070e29735ed546ca85f261846bc9101d90ce97f760791933"

ingress:
  host: dev.boutique.biroltilki.art
  tls:
    secretName: frontend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
