image:
  repository: acrboutiquedevweu.azurecr.io/frontend
  digest: "sha256:d22b7e13a9c9d3e8989bad0b0ab8271ab565570fb7ebfd1e28986febf5f9a2d5"

ingress:
  host: dev.boutique.biroltilki.art
  tls:
    secretName: frontend-dev-tls

# Schedule workloads to the user node pool (system pool is tainted CriticalAddonsOnly).
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
