image:
  repository: acrboutiqueprodweu.azurecr.io/cartservice
  digest: "sha256:REPLACE_WITH_PROD_DIGEST"

replicaCount: 2

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  port: 7070
  targetPort: 7070

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
