image:
  repository: acrboutiqueprodweu.azurecr.io/frontend
  digest: "sha256:a7ea6e5a8b398ef9070e29735ed546ca85f261846bc9101d90ce97f760791933"

ingress:
  className: nginx
  host: boutique.biroltilki.art
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    secretName: frontend-prod-tls

# Schedule workloads to prod node pool.
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
