apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-cart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "redis-cart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
