trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'variable-group-for-microservices'

parameters:
  - name: digest
    displayName: "Digest to promote (optional, ex: sha256:abcd...)"
    type: string
    default: ''

extends:
  template: ../templates/promote-image.yml
  parameters:
    stageName: PromoteBackendToStage
    stageDisplayName: Promote backend image from dev to stage
    deploymentName: PromoteBackendStage
    deploymentDisplayName: Import backend and create stage GitOps PR
    environmentName: promote-stage
    imageName: backend
    sourceAcrLoginServer: acrboutiquedevweu.azurecr.io
    targetAcrName: acrboutiquestageweu
    targetAcrLoginServer: acrboutiquestageweu.azurecr.io
    sourceValuesFile: gitops/envs/dev/values-backend.yaml
    targetValuesFile: gitops/envs/stage/values-backend.yaml
    githubRepository: btilki/microservices-cicd-on-azure-with-argocd-and-observability
    azureSubscriptionConnection: promotion-azure-connection
    promotionLabel: stage
    requiredSourceAcrRoles: AcrPull
    requiredTargetAcrRoles: AcrPull,AcrPush
    requiredReaderResourceGroups: rg-boutique-stage-weu,rg-boutique-prod-weu
    digest: ${{ parameters.digest }}
