trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'variable-group-for-microservices'

parameters:
  - name: digest
    displayName: "Digest to promote (optional, ex: sha256:abcd...)"
    type: string
    default: ''

extends:
  template: ../templates/promote-image.yml
  parameters:
    stageName: PromoteToProd
    stageDisplayName: Promote image from stage to prod
    deploymentName: PromoteProd
    deploymentDisplayName: Import and create prod GitOps PR
    environmentName: promote-prod
    imageName: frontend
    sourceAcrLoginServer: acrboutiquestageweu.azurecr.io
    targetAcrName: acrboutiqueprodweu
    targetAcrLoginServer: acrboutiqueprodweu.azurecr.io
    sourceValuesFile: gitops/envs/stage/values-frontend.yaml
    targetValuesFile: gitops/envs/prod/values-frontend.yaml
    githubRepository: btilki/microservices-cicd-on-azure-with-argocd-and-observability
    azureSubscriptionConnection: promotion-azure-connection
    promotionLabel: prod
    requiredSourceAcrRoles: AcrPull
    requiredTargetAcrRoles: AcrPush
    requiredReaderResourceGroups: rg-boutique-stage-weu,rg-boutique-prod-weu
    digest: ${{ parameters.digest }}
