apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cartservice-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: boutique-prod
  source:
    repoURL: https://github.com/btilki/micser-apps-Azure-Terraform-Helm-GitOps-monitoring.git
    targetRevision: main
    path: charts/cartservice
    helm:
      releaseName: cartservice
      valueFiles:
        - ../../gitops/envs/prod/values-cartservice.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
