apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: boutique-prod
  source:
    repoURL: https://github.com/btilki/microservice-apps-on-azure-using-terraform-helm-gitops-and-observability.git
    targetRevision: main
    path: charts/currencyservice
    helm:
      releaseName: currencyservice
      valueFiles:
        - ../../gitops/envs/prod/values-currencyservice.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
