image:
  repository: acrboutiquestageweu.azurecr.io/cartservice
  digest: "sha256:00826f3b030c1ffab3c8146ecba31b35dbda04fc29a619e60f7d68658cc8e073"

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 512Mi

service:
  port: 7070
  targetPort: 7070

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations:
  - key: env
    operator: Equal
    value: stage
    effect: NoSchedule
