image:
  repository: acrboutiquestageweu.azurecr.io/frontend
  digest: "sha256:c9d8927c1b646afe71888dfea9ba57bf4fbf53e2a273e8817d3d53529346c513"

googleDemo:
  enabled: false
  externalName: frontend.google-boutique.svc.cluster.local

replicaCount: 2

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  className: nginx
  host: stage.boutique.biroltilki.art
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    secretName: frontend-stage-tls

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
