image:
  repository: acrboutiquestageweu.azurecr.io/checkoutservice
  digest: "sha256:REPLACE_WITH_STAGE_DIGEST"

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 640Mi

nodeSelector:
  kubernetes.azure.com/mode: user

tolerations:
  - key: env
    operator: Equal
    value: stage
    effect: NoSchedule
