image:
  repository: acrboutiquestageweu.azurecr.io/backend
  digest: "sha256:801af4513ac121bfbd2da16ce4412d9800fd69ce13d7a0b35363b4e2f9dc97be"

ingress:
  host: api-stage.boutique.biroltilki.art
  tls:
    secretName: backend-stage-tls

# Schedule workloads to stage node pool.
nodeSelector:
  kubernetes.azure.com/mode: user

tolerations: []
