apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/btilki/micser-apps-Azure-Terraform-Helm-GitOps-monitoring.git
    targetRevision: main
    path: charts/currencyservice
    helm:
      releaseName: currencyservice
      valueFiles:
        - ../../gitops/envs/dev/values-currencyservice.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
