apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paymentservice-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: boutique-stage
  source:
    repoURL: https://github.com/btilki/microservices-cicd-on-azure-with-argocd-and-observability.git
    targetRevision: main
    path: charts/paymentservice
    helm:
      releaseName: paymentservice
      valueFiles:
        - ../../gitops/envs/stage/values-paymentservice.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
