apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalogservice-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: boutique-stage
  source:
    repoURL: https://github.com/btilki/microservice-apps-on-azure-using-terraform-helm-gitops-and-observability.git
    targetRevision: main
    path: charts/productcatalogservice
    helm:
      releaseName: productcatalogservice
      valueFiles:
        - ../../gitops/envs/stage/values-productcatalogservice.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
