apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: boutique-stage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Stage environment project for boutique services
  sourceRepos:
    - https://github.com/btilki/microservices-cicd-on-azure-with-argocd-and-observability.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: stage
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
