apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cart-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: boutique-stage
  source:
    repoURL: https://github.com/btilki/micser-apps-Azure-Terraform-Helm-GitOps-monitoring.git
    targetRevision: main
    path: charts/redis-cart
    helm:
      releaseName: redis-cart
      valueFiles:
        - ../../gitops/envs/stage/values-redis-cart.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
